services:
  - type: web
    name: eduresult-backend
    env: docker
    rootDir: backend
    plan: free
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 8080
      - key: DB_HOST
        fromDatabase:
          name: eduresult-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: eduresult-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: eduresult-db
          property: database
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: eduresult-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: eduresult-db
          property: password
      - key: JWT_SECRET
        generateValue: true

databases:
  - name: eduresult-db
    plan: free
