services:
  - type: web
    name: eduresult-backend
    env: docker
    rootDir: backend
    plan: free
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
